import Form from '@/components/form'
import Head from 'next/head'
import DataTable from 'react-data-table-component'

interface CellType {
  row: {
      id: number,
      email?: string,
      text?: string 
  }
}

export default function Home() {
  const tableData = [
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
    {
      id: 1,
      email: "fahim"
    },
    {
      id: 2,
      email: "fahim"
    },
    {
      id: 3,
      email: "fahim"
    },
  ]

  const columns = [
    {
      name : "Name",
      // selector : ({row}: CellType) => row.email
    },
    {
      name : "Email",
      selector : ({row}: CellType) =>{
        // row.email
      }
    },
    {
      name : "Email Body",
      selector : ({row}: CellType) =>{
        // row.email
      }
    },
    {
      name : "Date",
      selector : ({row}: CellType) =>{
        // row.email
      }
    },
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Form />

        <div className="dataTable">
          <DataTable
            rows={tableData}
            // data={tableData}
            columns={columns}
            data={tableData}
            pagination
            fixedHeader
            fixedHeaderScrollHeight='400px'
            selectableRows
            selectableRowsHighlight
            highlightOnHover
            paginationMode="server"
          />
        </div>

      </main>
    </>
  )
}
